format = """
[ $time\
$status\
$cmd_duration\
$fill\
$line_break \
$sudo\
$username\
$hostname\
$localip\
$git_branch\
$git_state\
$fill\
$line_break \
$directory\
$fill\
$line_break\
](bg:0)\
$jobs\
$character\
"""

[cmd_duration]
min_time = 0
format = "[$duration]($style) "
style = "bg:0 226"

[time]
disabled = false
format = "[$time]($style) "
style = "bg:0 51"
time_format = "%Y-%m-%d %T"

[status]
success_symbol = " "
format = "[$int]($style) "
disabled = false
style = "bg:0 bold 207"

[directory]
style = "bg:0 51"
truncate_to_repo = false
truncation_length = 20
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bg:0 51"

[character]
success_symbol = "[\\$](34)"
error_symbol = "[\\$](196)"

[git_state]
style = "bg:0 bold 207"
format = "[$state \\($progress_current/$progress_total\\)]($style)"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bg:0 39"
style_root = "bg:0 bold 207"

[hostname]
format = "[@$hostname]($style) "
trim_at = "."
style = "bg:0 207"
ssh_only = false

[localip]
ssh_only = false
disabled = false
style = "bg:0 39"

[sudo]
format = "[$symbol]($style)"
symbol = "⚡"
disabled = false
style = "bg:0 207"

[fill]
symbol = " "
style = "bg:0"
